/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedReuniaoInteligenteRouteImport } from './routes/_authenticated/reuniao-inteligente'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as AuthenticatedAcoesIndexRouteImport } from './routes/_authenticated/acoes/index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesClientIdRouteImport } from './routes/_authenticated/clientes/$clientId'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos/index'
import { Route as AuthenticatedProjetosProjectIdRouteImport } from './routes/_authenticated/projetos/$projectId'
import { Route as AuthenticatedReunioesIndexRouteImport } from './routes/_authenticated/reunioes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReuniaoInteligenteRoute =
  AuthenticatedReuniaoInteligenteRouteImport.update({
    id: '/reuniao-inteligente',
    path: '/reuniao-inteligente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcoesIndexRoute = AuthenticatedAcoesIndexRouteImport.update({
  id: '/acoes/',
  path: '/acoes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesClientIdRoute =
  AuthenticatedClientesClientIdRouteImport.update({
    id: '/clientes/$clientId',
    path: '/clientes/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosProjectIdRoute =
  AuthenticatedProjetosProjectIdRouteImport.update({
    id: '/projetos/$projectId',
    path: '/projetos/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReunioesIndexRoute =
  AuthenticatedReunioesIndexRouteImport.update({
    id: '/reunioes/',
    path: '/reunioes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/reuniao-inteligente': typeof AuthenticatedReuniaoInteligenteRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/acoes/': typeof AuthenticatedAcoesIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/reunioes/': typeof AuthenticatedReunioesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/reuniao-inteligente': typeof AuthenticatedReuniaoInteligenteRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/acoes': typeof AuthenticatedAcoesIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/reunioes': typeof AuthenticatedReunioesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/reuniao-inteligente': typeof AuthenticatedReuniaoInteligenteRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/_authenticated/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/_authenticated/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/_authenticated/acoes/': typeof AuthenticatedAcoesIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/reunioes/': typeof AuthenticatedReunioesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/reuniao-inteligente'
    | '/visao-geral'
    | '/clientes/$clientId'
    | '/projetos/$projectId'
    | '/acoes/'
    | '/clientes/'
    | '/projetos/'
    | '/reunioes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/reuniao-inteligente'
    | '/visao-geral'
    | '/clientes/$clientId'
    | '/projetos/$projectId'
    | '/acoes'
    | '/clientes'
    | '/projetos'
    | '/reunioes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/reuniao-inteligente'
    | '/_authenticated/visao-geral'
    | '/_authenticated/clientes/$clientId'
    | '/_authenticated/projetos/$projectId'
    | '/_authenticated/acoes/'
    | '/_authenticated/clientes/'
    | '/_authenticated/projetos/'
    | '/_authenticated/reunioes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reuniao-inteligente': {
      id: '/_authenticated/reuniao-inteligente'
      path: '/reuniao-inteligente'
      fullPath: '/reuniao-inteligente'
      preLoaderRoute: typeof AuthenticatedReuniaoInteligenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acoes/': {
      id: '/_authenticated/acoes/'
      path: '/acoes'
      fullPath: '/acoes/'
      preLoaderRoute: typeof AuthenticatedAcoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$clientId': {
      id: '/_authenticated/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/$projectId': {
      id: '/_authenticated/projetos/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reunioes/': {
      id: '/_authenticated/reunioes/'
      path: '/reunioes'
      fullPath: '/reunioes/'
      preLoaderRoute: typeof AuthenticatedReunioesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedReuniaoInteligenteRoute: typeof AuthenticatedReuniaoInteligenteRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedClientesClientIdRoute: typeof AuthenticatedClientesClientIdRoute
  AuthenticatedProjetosProjectIdRoute: typeof AuthenticatedProjetosProjectIdRoute
  AuthenticatedAcoesIndexRoute: typeof AuthenticatedAcoesIndexRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
  AuthenticatedReunioesIndexRoute: typeof AuthenticatedReunioesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedReuniaoInteligenteRoute: AuthenticatedReuniaoInteligenteRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedClientesClientIdRoute: AuthenticatedClientesClientIdRoute,
  AuthenticatedProjetosProjectIdRoute: AuthenticatedProjetosProjectIdRoute,
  AuthenticatedAcoesIndexRoute: AuthenticatedAcoesIndexRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
  AuthenticatedReunioesIndexRoute: AuthenticatedReunioesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
