// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oywwzmtqjssiagiizdrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95d3d6bXRxanNzaWFnaWl6ZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NTYxOTIsImV4cCI6MjEwMjIzMjE5Mn0.CCj9GnwxLSig4tqiQk12B3eoFVyic13mCYJCEz7cwh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});